### ISSUE TITLE
在安装tools/android-build.sh 时出现ssl_error_syscall in connection to crates.io:443

### ISSUE THREAD

**Issue by anjurochan** [consenlabs/token-core#101]
warning: spurious network error (1 tries remaining): [35] SSL connect error (LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to crates.io:443 )
warning: spurious network error (1 tries remaining): [35] SSL connect error (LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to crates.io:443 )

**Comment by XuNeal** [comment]
第一个报错是因为你网络问题
第二个需要确认你是否安装了对应的NDK相关工具

**Comment by anjurochan** [comment]
[target.aarch64-linux-android]
ar = "/Users/user/Library/Android/sdk/ndk/23.0.7599858/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android-ar"
linker = "/Users/user/Library/Android/sdk/ndk/23.0.7599858/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android22-clang"

[target.armv7-linux-androideabi]
ar = "/Users/user/Library/Android/sdk/ndk/23.0.7599858/toolchains/llvm/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-ar"
linker = "/Users/user/Library/Android/sdk/ndk/23.0.7599858/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi22-clang"

[target.i686-linux-android]
ar = "/Users/user/Library/Android/sdk/ndk/23.0.7599858/toolchains/llvm/prebuilt/darwin-x86_64/bin/i686-linux-android-ar"
linker = "/Users/user/Library/Android/sdk/ndk/23.0.7599858/toolchains/llvm/prebuilt/darwin-x86_64/bin/i686-linux-android22-clang"


[target.x86_64-linux-android]
ar = "/Users/user/Library/Android/sdk/ndk/23.0.7599858/toolchains/llvm/prebuilt/darwin-x86_64/bin/x86_64-linux-android-ar"
linker = "/Users/user/Library/Android/sdk/ndk/23.0.7599858/toolchains/llvm/prebuilt/darwin-x86_64/bin/x86_64-linux-android22-clang"

上面是~/.cargo/config的配置 位于 token-core的根目录

但是执行 tools/android-example-build.sh却报错误

Failed to find tool. Is `x86_64-linux-android-ar` installed?
Failed to find tool. Is `i686-linux-android-ar` installed?

请问如何解决 谢谢

**Comment by anjurochan** [comment]
to

**Comment by anjurochan** [comment]
tokenx build successfully whille change 23.0.7599858 to 22.

**Comment by anjurochan** [comment]
感谢回复 ，已经按照提示完整安装了！

**Comment by anjurochan** [comment]
i already follow the instructiion of
https://github.com/consenlabs/token-core/tree/dev/examples/RN,

but when i click "create" button in RN EXAMPLE,there is some error in logs
like

[TypeError: null is not an object (evaluating 'TcxAPI.callTcxApi')]

但是提示上面的问题


[image: image.png]

[image: image.png]



请问是不是没有正常关联TOKENCOREX？

**Comment by XuNeal** [comment]
可能是 rn 的example 维护没有那么及时了。你可以先看一下
- TokenCoreX的API
- JNA 或者 Swift 调用 C 接口示例
- RN 如何调用原生的接口
-

**Comment by anjurochan** [comment]
- 请问RN 如何调用原生的接口 是指 react native 调用c接口对吗
   -
   - [image: image.png]

   - 再请问下 在target ->release->build的这些是不是已经代表 TokenCoreX已经是编译成功了

   只是RN没有成功的调用到的意思是吗

   [image: image.png]

**Comment by XuNeal** [comment]
看不到你的图片

**Comment by XuNeal** [comment]
RN如何调用原生是指如何调用 Android 或者 iOS的代码 参见这里 https://reactnative.dev/docs/native-modules-android

**Comment by anjurochan** [comment]
感谢指导

请问有没有TELEGRAM啊 方便加您下吗

**Comment by anjurochan** [comment]
LOG  Running "RN" with {"rootTag":1}

 LOG  -------------- hd_store_create -------------------

 LOG  hd_store_create params {"password":"","name":"","passwordHint":""}

 LOG  hd_store_create hexStr:
0a0f68645f73746f72655f63726561746512190a0f68645f73746f72655f63726561746512060a0012001a00

 WARN  hd_store_create error [TypeError: null is not an object (evaluating
'TcxAPI.callTcxApi')]

 WARN  hd_store_create errBuf {"data": [], "type": "Buffer"}

 WARN  hd_store_create decode err {}

**Comment by anjurochan** [comment]
cp ../target/aarch64-linux-android/release/libtcx.so $JNI_LIBS/arm64-v8a
cp ../target/armv7-linux-androideabi/release/libtcx.so $JNI_LIBS/armeabi-v7a
cp ../target/i686-linux-android/release/libtcx.so $JNI_LIBS/x86
cp ../target/x86_64-linux-android/release/libtcx.so $JNI_LIBS/x86_64
查了RN目录下的android，.so都有COPY成功

但就是一直出现 [TypeError: null is not an object (evaluating
'TcxAPI.callTcxApi')]，实在不知要如何才能调用到 TOKENCOREX，

请问能不能指点一下 谢谢

**Comment by XuNeal** [comment]
看起来是Android这边没有合适的曝露方法给RN。你能先确认你Android 或者 iOS 能跑通吗？这部分应该https://reactnative.dev/docs/native-modules-android 和这里有关

**Comment by anjurochan** [comment]
pushd ./libs/secp256k1

AR=$ANDROID_NDK_TOOLCHAINS/aarch64-linux-android-ar CC=
$ANDROID_NDK_TOOLCHAINS/aarch64-linux-android22-clang cargo build --target
aarch64-linux-android --release
AR=$ANDROID_NDK_TOOLCHAINS/arm-linux-androideabi-ar CC=
$ANDROID_NDK_TOOLCHAINS/armv7a-linux-androideabi22-clang cargo build
--target armv7-linux-androideabi --release
AR=$ANDROID_NDK_TOOLCHAINS/i686-linux-android-ar
CC=$ANDROID_NDK_TOOLCHAINS/i686-linux-android22-clang
cargo build --target i686-linux-android --release
AR=$ANDROID_NDK_TOOLCHAINS/x86_64-linux-android-ar CC=
$ANDROID_NDK_TOOLCHAINS/x86_64-linux-android22-clang cargo build --target
x86_64-linux-android --release

popd

pushd ./tcx

在BUILD时候提示 ./libs/secp256k1 这个目录为空

请问下 是不是这个问题 ANDROID的我试试先

**Comment by anjurochan** [comment]
又重新试了下 发现是.SH 没有成功生成 secp256k1

而有生成 tcx

能否帮忙解决下 麻烦您了


#!/bin/bash

export ANDROID_NDK_TOOLCHAINS=$HOME
/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin
export PATH=$ANDROID_NDK_TOOLCHAINS:$PATH

JNI_LIBS=examples/android/tokencorex/src/main/jniLibs
if [ ! -d $JNI_LIBS ]; then
mkdir $JNI_LIBS
mkdir $JNI_LIBS/arm64-v8a
mkdir $JNI_LIBS/armeabi-v7a
mkdir $JNI_LIBS/x86
mkdir $JNI_LIBS/x86_64
fi

pushd $ANDROID_NDK_TOOLCHAINS

if [ ! -d aarch64-linux-android-clang ]; then
ln -s -f aarch64-linux-android22-clang aarch64-linux-android-clang
ln -s -f armv7a-linux-androideabi22-clang arm-linux-androideabi-clang
ln -s -f i686-linux-android22-clang i686-linux-android-clang
ln -s -f x86_64-linux-android22-clang x86_64-linux-android-clang
fi
popd

# pushd libs/secp256k1
# JNI_LIBS=../../examples/android/tokencorex/src/main/jniLibs

# cargo build --target aarch64-linux-android --release
# cargo build --target armv7-linux-androideabi --release
# cargo build --target i686-linux-android --release
# cargo build --target x86_64-linux-android --release


# cp target/aarch64-linux-android/release/libsecp256k1.so
$JNI_LIBS/arm64-v8a
# cp target/armv7-linux-androideabi/release/libsecp256k1.so
$JNI_LIBS/armeabi-v7a
# cp target/i686-linux-android/release/libsecp256k1.so $JNI_LIBS/x86
# cp target/x86_64-linux-android/release/libsecp256k1.so $JNI_LIBS/x86_64
pushd secp256k1
LIBS=../examples/android/tokencorex/src/main/libs

cargo build --target aarch64-linux-android --release
cargo build --target armv7-linux-androideabi --release
cargo build --target i686-linux-android --release
cargo build --target x86_64-linux-android --release


cp ../target/aarch64-linux-android/release/libsecp256k1.so $LIBS/arm64-v8a
cp ../target/armv7-linux-androideabi/release/libsecp256k1.so $LIBS
/armeabi-v7a
cp ../target/i686-linux-android/release/libsecp256k1.so $LIBS/x86
cp ../target/x86_64-linux-android/release/libsecp256k1.so $LIBS/x86_64


popd


pushd tcx
JNI_LIBS=../examples/android/tokencorex/src/main/jniLibs

cargo build --target aarch64-linux-android --release
cargo build --target armv7-linux-androideabi --release
cargo build --target i686-linux-android --release
cargo build --target x86_64-linux-android --release

cp ../target/aarch64-linux-android/release/libtcx.so $JNI_LIBS/arm64-v8a
cp ../target/armv7-linux-androideabi/release/libtcx.so $JNI_LIBS/armeabi-v7a
cp ../target/i686-linux-android/release/libtcx.so $JNI_LIBS/x86
cp ../target/x86_64-linux-android/release/libtcx.so $JNI_LIBS/x86_64

popd

**Comment by XuNeal** [comment]
secp256k1 应该是一个git submodules 需要你克隆的时候完整的克隆下来

**Comment by anjurochan** [comment]
[submodule "libs/secp256k1"]
path = libs/secp256k1
url = https://github.com/consenlabs/rust-secp256k1.git
已经把rust-secp256k1 GIT下来了

然后是不是把rust-secp256k1放到 根目录 token-core的目录 libs/secp256k1下面

再执行tools/android-example-build.sh

**Comment by anjurochan** [comment]
error: current package believes it's in a workspace when it's not:
current:
/Users/user/Desktop/ReactNative/token-core/libs/secp256k1/Cargo.toml
workspace: /Users/user/Desktop/ReactNative/token-core/Cargo.toml

this may be fixable by adding `libs/secp256k1` to the `workspace.members`
array of the manifest located at:
/Users/user/Desktop/ReactNative/token-core/Cargo.toml
Alternatively, to keep it out of the workspace, add the package to the
`workspace.exclude` array, or add an empty `[workspace]` table to the
package's manifest.
error: current package believes it's in a workspace when it's not:
current:
/Users/user/Desktop/ReactNative/token-core/libs/secp256k1/Cargo.toml
workspace: /Users/user/Desktop/ReactNative/token-core/Cargo.toml

出现上面的错误 请问如何解决？

**Comment by anjurochan** [comment]
cp target/aarch64-linux-android/release/libsecp256k1.so $JNI_LIBS/arm64-v8a


无论怎么试 就是生成不了 libsecp256k1.so ,

driving me crazy now... could u please give me a hand,thanks!

>
>
>

**Comment by anjurochan** [comment]
r u still there,

still fail to make libsecp256k1.so

**Comment by anjurochan** [comment]
直到切换为UBUNTU才成功安装了 libsecp256k1.so

anyway thanks!
