### ISSUE TITLE
请问哪里可以下载上次活动的ppt

### ISSUE THREAD

**Issue by vae520283995** [consenlabs/token-core#30]
<sub>Sent from <a href="https://itunes.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by kaichen** [comment]
请问是哪一次的活动？

**Comment by vae520283995** [comment]
> 请问是哪一次的活动？

Rust 在移动端钱包的跨平台实践 - imToken | Kai
这个活动,里面的ppt有讲token core x的架构
