### ISSUE TITLE
suggestion for `CkbAddress#is_valid`

### ISSUE THREAD

**Issue by quake** [consenlabs/token-core#51]
This method should check code hash index and args lens, java sdk unit test for your reference:
https://github.com/nervosnetwork/ckb-sdk-java/blob/develop/ckb/src/test/java/utils/AddressParserTest.java#L170-L200

**Comment by XuNeal** [comment]
Thanks for the suggestion. I have add more validation to Address::is_valid which follow the implement in `AddressParser`
