### ISSUE TITLE
update to prost 0.6

### ISSUE THREAD

**Issue by flipchan** [consenlabs/token-core#65]
Hey,
Prost 0.5 is unstable(stackoverflow found), plz update to .6
link to more info:
https://rust.firosolutions.com/paste/KMwbKq1OjofTF3aRROgWSiq8U3bbmQQlxQNSeA6vf8I

**Comment by XuNeal** [comment]
Sorry for reply so late.
 This issue will be fixed in https://github.com/consenlabs/token-core/pull/68

**Comment by flipchan** [comment]
Great!
