### ISSUE TITLE
没有实现 ethereum 吗？

### ISSUE THREAD

**Issue by Pony-Unicorn** [consenlabs/token-core#66]
没有实现 ethereum 吗？

**Comment by Pony-Unicorn** [comment]
有计划加入 ethereum 签名、地址生成等功能的实现吗？

**Comment by kaichen** [comment]
Ethereum, Bitcoin 等仍未迁移至 rust 实现，目前依然是采用 Swift/Java，在完成一些新链的接入后会将其迁移至本仓库，感谢关注

https://github.com/consenlabs/token-core-ios/tree/master/Sources/Foundation/Ethereum
