### ISSUE TITLE
hdStoreDerive 返回错误error

### ISSUE THREAD

**Issue by lnssh3** [consenlabs/token-core#70]
walletAPI.hdStoreCreate创建成功之后拿到参数 调用 walletAPI.hdStoreDerive后 返回 error：1211756e737570706f727465645f636861696e

**Comment by XuNeal** [comment]
返回的信息可以使用Response这个结构体decode一下看看。
我用你返回的错误信息decode出来是   
`Response { is_success: false, error: "unsupported_chain" }`

可能是你传入的参数有误。相关的派生测试代码参见：
https://github.com/consenlabs/token-core/blob/9991695bd466b8cccc260828911e98cff56e4c12/tcx/src/lib.rs#L511

**Comment by XuNeal** [comment]
This issue will be closed as it has not update for a long time. You can reopen it if you have any other problem
