### ISSUE TITLE
MaxOS 链接错误

### ISSUE THREAD

**Issue by SzeChuanChilliSauce** [consenlabs/token-core#71]
![image](https://user-images.githubusercontent.com/26214341/83847198-6d319b80-a73e-11ea-9f8c-2cd04ad973e6.png)
我在mac上用rust源码编译为android库，按照文档的步骤，出现了ld: unknown option: --as-need，请教下，怎么解决？

**Comment by SzeChuanChilliSauce** [comment]
mtlib2是我自己写的一个测试项目，我想把它编译为安卓库。

**Comment by XuNeal** [comment]
参考一下这个编译脚本  https://github.com/consenlabs/token-core/blob/dev/tools/android-example-build.sh#L17
指定的target是android的话他会去ANDROID_NDK_TOOLCHAINS等环境变量寻找相应的编译工具。

**Comment by SzeChuanChilliSauce** [comment]
> 参考一下这个编译脚本 https://github.com/consenlabs/token-core/blob/dev/tools/android-example-build.sh#L17
> 指定的target是android的话他会去ANDROID_NDK_TOOLCHAINS等环境变量寻找相应的编译工具。
好的，我先看看，感谢。

**Comment by SzeChuanChilliSauce** [comment]
> 参考一下这个编译脚本 https://github.com/consenlabs/token-core/blob/dev/tools/android-example-build.sh#L17
> 指定的target是android的话他会去ANDROID_NDK_TOOLCHAINS等环境变量寻找相应的编译工具。

请问android上使用的api是用jni包装过的吗？我没看见项目中jni包装呢？
