### ISSUE TITLE
Android JNI

### ISSUE THREAD

**Issue by SzeChuanChilliSauce** [consenlabs/token-core#72]
请教一下：
项目中的api是通过JNI包装过的吗？
代码中我没见看见JNI相关的包装，看编译手册和example项目，是直接编译然后load library，安卓就直接调用。

**Comment by XuNeal** [comment]
项目使用的JNA，比JNI使用上要友好一些，可以参见: https://github.com/java-native-access/jna

**Comment by SzeChuanChilliSauce** [comment]
> 项目使用的JNA，比JNI使用上要友好一些，可以参见: https://github.com/java-native-access/jna

谢谢！
