### ISSUE TITLE
IOS binding

### ISSUE THREAD

**Issue by SzeChuanChilliSauce** [consenlabs/token-core#73]
请问：ios上是如何调用rust接口的？
我其他的项目是把rust函数写成C风格的接口。我看贵项目中写的rust原生接口，请问你们是怎么做的。

**Comment by XuNeal** [comment]
不太确定你具体问的是哪一步，你可以看看这篇文章是否可以给你答案：https://medium.com/visly/rust-on-ios-39f799b3c1dd

**Comment by SzeChuanChilliSauce** [comment]
> 不太确定你具体问的是哪一步，你可以看看这篇文章是否可以给你答案：https://medium.com/visly/rust-on-ios-39f799b3c1dd

好的，谢谢。
