### ISSUE TITLE
未找到 ios-token-v2-release-build.sh 

### ISSUE THREAD

**Issue by mghnmtt** [consenlabs/token-core#79]
请问后面会考虑开源ios-token-v2-release-build.sh 么
打包完.h文件只有 四个方法

**Comment by mghnmtt** [comment]
<img width="786" alt="截屏2020-08-12 下午5 30 27" src="https://user-images.githubusercontent.com/13725793/89999633-a26be400-dcc1-11ea-9788-ad2aa8ded21b.png">
<img width="931" alt="截屏2020-08-12 下午5 30 33" src="https://user-images.githubusercontent.com/13725793/89999641-a4ce3e00-dcc1-11ea-92b8-b341003c8d50.png">

**Comment by xwartz** [comment]
`ios-token-v2-release-build.sh` 是内部项目在使用的，你可以参考 tools 目录下的 `.sh`，只是生成的文件目录不一样而已。
