### ISSUE TITLE
iOS Example can not run with XCode 12

### ISSUE THREAD

**Issue by matteozero** [consenlabs/token-core#82]
1.  init_token_core_x() method not found.
2. Buffer is not define.

Cloud you please fixed it.
<img width="507" alt="1" src="https://user-images.githubusercontent.com/69132061/96553680-1640f300-12e8-11eb-9a34-bdf65784bc91.png">
<img width="933" alt="2" src="https://user-images.githubusercontent.com/69132061/96553698-1b9e3d80-12e8-11eb-8ed9-db8a0ea0ded8.png">

**Comment by ZYanMing** [comment]
I have the same question. How to resolve this question? Should i use Xcode11 only?
