### ISSUE TITLE
安装基础组件报错

### ISSUE THREAD

**Issue by tiantianlikeu** [consenlabs/token-core#84]
我在执行这条命令后：
token-core git:(dev) rustup target add aarch64-apple-ios armv7-apple-ios armv7s-apple-ios i386-apple-ios x86_64-apple-ios
出现以下信息，无法正常安装组件
info: component 'rust-std' for target 'aarch64-apple-ios' is up to date
error: component 'rust-std' for target 'armv7-apple-ios' is unavailable for download for channel 1.44.0

**Comment by XuNeal** [comment]
rust 的交叉编译已经逐渐出去 32位的了，你可以将i386 和armv7s 相关编译移除掉即可

**Comment by tiantianlikeu** [comment]
好的，我试试。去除之后，可以正常编译吗？

**Comment by tiantianlikeu** [comment]
谢谢，很完美的解决了我的问题，正常编译通过。
